# ---Environment Configs---
env_name: gymnax

scenario:
  name: MountainCar-v0
  task_name: mountain_car

kwargs: {}

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return
