# ---MLP QR-DQN Networks---
actor_network:
  pre_torso:
    _target_: zenoqx.networks.torso.MLPTorso
    layer_sizes: [256, 256]
    use_layer_norm: False
    activation: silu
  action_head:
    _target_: zenoqx.networks.heads.QuantileDiscreteQNetwork
    num_quantiles: ${system.num_quantiles}
